### ISSUE TITLE
Class name must be a valid object or a string

### ISSUE THREAD

**Issue by tanteng** [Zizaco/entrust#500]
php artisan entrust:migration

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class name must be a valid object or a string

in config/auth.php

add:

`
    'model' => 'App\Models\User',
    'table' => 'users',
`

Then created User Model:

```php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Model
{
    use EntrustUserTrait; // add this trait to your user model

}
```

That's OK!

**Comment by psbhanu** [comment]
I got same issue with Laravel 5.2. 
To resolve Locate `./vendor/zizaco/entrust/src/commands/MigrationCommand.php`
and change code (Line number 84 and 85) from:

```
$usersTable  = Config::get('auth.table');
$userModel   = Config::get('auth.model');
```

To:

```
$usersTable  = Config::get('auth.providers.users.table');
$userModel   = Config::get('auth.providers.users.model');	
```

PS. Remember to Run command `composer dump-autoload` after performing changes.

Thanks.

**Comment by diabolicfreak** [comment]
@psbhanu Thanks that worked

**Comment by hihoZhou** [comment]
@psbhanu  Thanks that worked

**Comment by MichaelObi** [comment]
These fixes have to be taken seriously! Right now I maintain my own fork of this project where I make the fixes for my own use because the problems are solved but never get merged in! it's my best package for access control but it's becoming a pain to use.

**Comment by digitlimit** [comment]
I had to change line 86 and 87 of MigrationCommand to:
    config('auth.table');
    config('auth.model');

And that got it working

**Comment by Shibly** [comment]
Using Laravel Framework version 5.2.36 , no fixes are working. Still getting error 
FatalThrowableError in Model.php line 945:
Class name must be a valid object or a string

**Comment by santigarcor** [comment]
You could use this [fork](https://github.com/santigarcor/laratrust) a friend of mine and i are mantaining. we have solved a lot of problems of this package

**Comment by chandirasekaranid** [comment]
FatalThrowableError in Model.php line 949:
Class name must be a valid object or a string

**Comment by nejtr0n** [comment]
same issue on laravel 5.2.39

**Comment by nejtr0n** [comment]
Try to change EntrustRoleTrait line 51 to 
```
        return $this->belongsToMany(Config::get('auth.providers.users.model'), Config::get('entrust.role_user_table'),Config::get('entrust.role_foreign_key'),Config::get('entrust.user_foreign_key'));
       // return $this->belongsToMany(Config::get('auth.providers.users.model'), Config::get('entrust.role_user_table'));
```

**Comment by tabirkeland** [comment]
I just removed Entrust and replaced it with @santigarcor 's package.  Solved my issues.

**Comment by Fenn-CS** [comment]
Well I still get the error, even though this 
$usersTable  = Config::get('auth.providers.users.table');
$userModel   = Config::get('auth.providers.users.model'); 
is already present in the file

**Comment by luukverhoeven** [comment]
Same issue here:	
`Symfony\Component\Debug\Exception\FatalThrowableError: Class name must be a valid object or a string in `

`Illuminate\Database\Eloquent\Model->belongsToMany(NULL, 'role_user', 'role_id', 'user_id')`

**Comment by MichaelObi** [comment]
i would recommend moving to [Laratrust](https://github.com/santigarcor/laratrust). It's a fork of Entrust that is being actively maintained by @santigarcor .

**Comment by hak11** [comment]
add line **config/auth.php**
```

'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
            'table' => 'users',
        ],
    ],
```

Good luck :)

**Comment by FellowsDevel** [comment]
Thank tanteng!!!

Adding:
'model' => 'App\User',
'table' => 'users',

to the auth.php did the trick

**Comment by jameskandau** [comment]
Adding a users method in Role model solved the issue for me
  public function users()
{
   return $this->belongsToMany(Config::get('auth.providers.users.model'),Config::get('entrust.role_user_table'),Config::get('entrust.role_foreign_key'),Config::get('entrust.user_foreign_key'));
    
}

**Comment by karakanb** [comment]
Applied the solution @jameskandau provided, it solved the issue in Laravel 5.4.28.

```php
public function users() {
    return $this->belongsToMany(
        Config::get('auth.providers.users.model'),
        Config::get('entrust.role_user_table'),
        Config::get('entrust.role_foreign_key'),
        Config::get('entrust.user_foreign_key'));
}
```

**Comment by amenk** [comment]
Worked for me as well ... but Shouldn't that be in the Entrust package so there is no need to always fix it in each application, or am I getting something wrong.

Please consider reopening.
