### ISSUE TITLE
Different Return Type for `save()` Method

### ISSUE THREAD

**Issue by wzulfikar** [Zizaco/entrust#555]
_I'm using "zizaco/entrust": "5.2.x-dev" with Laravel 5.1_

I use `Zizaco\Entrust\Traits\EntrustUserTrait` in my `User` model and since then, I noticed that `save()` method of my `User` model is no more returning any value: it returns null, always.

Turns out that `EntrustUserTrait` override `save()` method from eloquent. The issue is, the `save()` method in eloquent returns boolean (value of `$saved`) while in `EntrustUserTrait`, it doesn't return anything. So, it's not substitutable.

`EntrustUserTrait` :
![2016-03-25_22-33-38](https://cloud.githubusercontent.com/assets/7823011/14046080/d0fc4746-f2d9-11e5-9f5b-271ef4cdf955.png)

`Eloquent\Model` :
![2016-03-25_22-34-07](https://cloud.githubusercontent.com/assets/7823011/14046102/e5f76da6-f2d9-11e5-8064-6caa03424074.png)

_My thought_ : 
![2016-03-25_22-38-44](https://cloud.githubusercontent.com/assets/7823011/14046163/631ecbb2-f2da-11e5-82b5-604ee12978f2.png)

**Comment by santigarcor** [comment]
I think it is already solved check #547

**Comment by wzulfikar** [comment]
oh ok just checked it. thanks @santigarcor !

**Comment by wzulfikar** [comment]
Just checked the code again @santigarcor : apparently only `EntrustRoleTrait` is solved. `EntrustUserTrait` still doesn't return value from parent.
![2016-06-19_10-37-43](https://cloud.githubusercontent.com/assets/7823011/16174852/f1dcde08-3609-11e6-9c31-8602a543f15d.png)

**Comment by Kristories** [comment]
Same here `EntrustUserTrait@save()` still return `null` 😢

**Comment by wzulfikar** [comment]
*closed. see #431
